apiVersion: v1
kind: Secret
metadata:
  name: realworld-secret
  namespace: realworld
  labels:
    app: realworld-api
type: Opaque
stringData:
  database-username: "<REPLACE_WITH_DB_USERNAME>"
  database-password: "<REPLACE_WITH_DB_PASSWORD>"
  jwt-secret: "<REPLACE_WITH_JWT_SECRET>"
